package com.card.iso8583.spec;

import com.card.iso8583.model.FieldDefinition;
import com.card.iso8583.model.FieldDefinition.*;
import com.card.iso8583.model.FieldType;

import static com.card.iso8583.model.FieldType.*;

/**
 * CARDNET-style ISO 8583 field definitions.
 * Full 128-field layout based on ISO 8583:1987.
 */
public final class CardnetSpec {

    private CardnetSpec() {}

    private static final MessageSpec INSTANCE = buildSpec();

    public static MessageSpec getInstance() {
        return INSTANCE;
    }

    private static MessageSpec buildSpec() {
        return MessageSpec.builder()
                // — Primary Bitmap Fields (2–64) —
                .add(new LlVar(2, "PAN", BCD_NUMERIC, 19))
                .add(new Fixed(3, "Processing Code", BCD_NUMERIC, 6))
                .add(new Fixed(4, "Amount Transaction", BCD_AMOUNT, 12))
                .add(new Fixed(5, "Amount Settlement", BCD_AMOUNT, 12))
                .add(new Fixed(6, "Amount Cardholder Billing", BCD_AMOUNT, 12))
                .add(new Fixed(7, "Transmission Date Time", BCD_NUMERIC, 10))
                .add(new Fixed(8, "Amount Cardholder Billing Fee", BCD_AMOUNT, 8))
                .add(new Fixed(9, "Conversion Rate Settlement", BCD_NUMERIC, 8))
                .add(new Fixed(10, "Conversion Rate Cardholder", BCD_NUMERIC, 8))
                .add(new Fixed(11, "STAN", BCD_NUMERIC, 6))
                .add(new Fixed(12, "Local Time", BCD_NUMERIC, 6))
                .add(new Fixed(13, "Local Date", BCD_NUMERIC, 4))
                .add(new Fixed(14, "Expiration Date", BCD_NUMERIC, 4))
                .add(new Fixed(15, "Settlement Date", BCD_NUMERIC, 4))
                .add(new Fixed(16, "Currency Conversion Date", BCD_NUMERIC, 4))
                .add(new Fixed(17, "Capture Date", BCD_NUMERIC, 4))
                .add(new Fixed(18, "MCC", BCD_NUMERIC, 4))
                .add(new Fixed(19, "Acquiring Country Code", BCD_NUMERIC, 3))
                .add(new Fixed(20, "PAN Extended Country Code", BCD_NUMERIC, 3))
                .add(new Fixed(21, "Forwarding Country Code", BCD_NUMERIC, 3))
                .add(new Fixed(22, "POS Entry Mode", BCD_NUMERIC, 3))
                .add(new Fixed(23, "Card Sequence Number", BCD_NUMERIC, 3))
                .add(new Fixed(24, "Network International ID", BCD_NUMERIC, 3))
                .add(new Fixed(25, "POS Condition Code", BCD_NUMERIC, 2))
                .add(new Fixed(26, "POS PIN Capture Code", BCD_NUMERIC, 2))
                .add(new Fixed(27, "Auth ID Response Length", BCD_NUMERIC, 1))
                .add(new Fixed(28, "Amount Transaction Fee", ALPHA, 9))
                .add(new Fixed(29, "Amount Settlement Fee", ALPHA, 9))
                .add(new Fixed(30, "Amount Transaction Processing Fee", ALPHA, 9))
                .add(new Fixed(31, "Amount Settlement Processing Fee", ALPHA, 9))
                .add(new LlVar(32, "Acquiring Inst ID", BCD_NUMERIC, 11))
                .add(new LlVar(33, "Forwarding Inst ID", BCD_NUMERIC, 11))
                .add(new LlVar(34, "PAN Extended", BCD_NUMERIC, 28))
                .add(new LlVar(35, "Track 2 Data", ALPHA, 37))
                .add(new LllVar(36, "Track 3 Data", ALPHA, 104))
                .add(new Fixed(37, "Retrieval Ref Number", ALPHA, 12))
                .add(new Fixed(38, "Auth ID Response", ALPHA, 6))
                .add(new Fixed(39, "Response Code", ALPHA, 2))
                .add(new Fixed(40, "Service Restriction Code", ALPHA, 3))
                .add(new Fixed(41, "Terminal ID", ALPHA, 8))
                .add(new Fixed(42, "Merchant ID", ALPHA, 15))
                .add(new Fixed(43, "Merchant Name Location", ALPHA, 40))
                .add(new LlVar(44, "Additional Response Data", ALPHA, 25))
                .add(new LlVar(45, "Track 1 Data", ALPHA, 76))
                .add(new LllVar(46, "Additional Data ISO", ALPHA, 999))
                .add(new LllVar(47, "Additional Data National", ALPHA, 999))
                .add(new LllVar(48, "Additional Data Private", ALPHA, 999))
                .add(new Fixed(49, "Currency Code Transaction", BCD_NUMERIC, 3))
                .add(new Fixed(50, "Currency Code Settlement", BCD_NUMERIC, 3))
                .add(new Fixed(51, "Currency Code Cardholder", BCD_NUMERIC, 3))
                .add(new Fixed(52, "PIN Data", BINARY, 8))
                .add(new Fixed(53, "Security Control Info", BCD_NUMERIC, 16))
                .add(new LllVar(54, "Additional Amounts", ALPHA, 120))
                .add(new LllVar(55, "EMV Data", BINARY, 999))
                .add(new LllVar(56, "Reserved ISO", ALPHA, 999))
                .add(new LllVar(57, "Reserved National", ALPHA, 999))
                .add(new LllVar(58, "Reserved National 2", ALPHA, 999))
                .add(new LllVar(59, "Reserved National 3", ALPHA, 999))
                .add(new LllVar(60, "Private Use", ALPHA, 60))
                .add(new LllVar(61, "Private Use 2", ALPHA, 99))
                .add(new LllVar(62, "Private Use 3", ALPHA, 999))
                .add(new LllVar(63, "Private Use 4", ALPHA, 999))
                .add(new Fixed(64, "MAC", BINARY, 8))

                // — Secondary Bitmap Fields (65–128) —
                .add(new Fixed(65, "Bitmap Tertiary", BINARY, 8))
                .add(new Fixed(66, "Settlement Code", BCD_NUMERIC, 1))
                .add(new Fixed(67, "Extended Payment Code", BCD_NUMERIC, 2))
                .add(new Fixed(68, "Receiving Country Code", BCD_NUMERIC, 3))
                .add(new Fixed(69, "Settlement Country Code", BCD_NUMERIC, 3))
                .add(new Fixed(70, "Network Mgmt Info Code", BCD_NUMERIC, 3))
                .add(new Fixed(71, "Message Number", BCD_NUMERIC, 4))
                .add(new Fixed(72, "Message Number Last", BCD_NUMERIC, 4))
                .add(new Fixed(73, "Date Action", BCD_NUMERIC, 6))
                .add(new Fixed(74, "Credits Number", BCD_NUMERIC, 10))
                .add(new Fixed(75, "Credits Reversal Number", BCD_NUMERIC, 10))
                .add(new Fixed(76, "Debits Number", BCD_NUMERIC, 10))
                .add(new Fixed(77, "Debits Reversal Number", BCD_NUMERIC, 10))
                .add(new Fixed(78, "Transfer Number", BCD_NUMERIC, 10))
                .add(new Fixed(79, "Transfer Reversal Number", BCD_NUMERIC, 10))
                .add(new Fixed(80, "Inquiries Number", BCD_NUMERIC, 10))
                .add(new Fixed(81, "Authorizations Number", BCD_NUMERIC, 10))
                .add(new Fixed(82, "Credits Processing Fee", BCD_NUMERIC, 12))
                .add(new Fixed(83, "Credits Transaction Fee", BCD_NUMERIC, 12))
                .add(new Fixed(84, "Debits Processing Fee", BCD_NUMERIC, 12))
                .add(new Fixed(85, "Debits Transaction Fee", BCD_NUMERIC, 12))
                .add(new Fixed(86, "Credits Amount", BCD_NUMERIC, 16))
                .add(new Fixed(87, "Credits Reversal Amount", BCD_NUMERIC, 16))
                .add(new Fixed(88, "Debits Amount", BCD_NUMERIC, 16))
                .add(new Fixed(89, "Debits Reversal Amount", BCD_NUMERIC, 16))
                .add(new Fixed(90, "Original Data Elements", BCD_NUMERIC, 42))
                .add(new Fixed(91, "File Update Code", ALPHA, 1))
                .add(new Fixed(92, "File Security Code", ALPHA, 2))
                .add(new Fixed(93, "Response Indicator", ALPHA, 5))
                .add(new Fixed(94, "Service Indicator", ALPHA, 7))
                .add(new Fixed(95, "Replacement Amounts", ALPHA, 42))
                .add(new Fixed(96, "Message Security Code", BINARY, 8))
                .add(new Fixed(97, "Amount Net Settlement", BCD_AMOUNT, 17))
                .add(new Fixed(98, "Payee", ALPHA, 25))
                .add(new LlVar(99, "Settlement Inst ID", BCD_NUMERIC, 11))
                .add(new LlVar(100, "Receiving Inst ID", BCD_NUMERIC, 11))
                .add(new LlVar(101, "File Name", ALPHA, 17))
                .add(new LlVar(102, "Account ID 1", ALPHA, 28))
                .add(new LlVar(103, "Account ID 2", ALPHA, 28))
                .add(new LllVar(104, "Transaction Description", ALPHA, 100))
                .add(new LllVar(105, "Reserved ISO 5", ALPHA, 999))
                .add(new LllVar(106, "Reserved ISO 6", ALPHA, 999))
                .add(new LllVar(107, "Reserved ISO 7", ALPHA, 999))
                .add(new LllVar(108, "Reserved ISO 8", ALPHA, 999))
                .add(new LllVar(109, "Reserved ISO 9", ALPHA, 999))
                .add(new LllVar(110, "Reserved ISO 10", ALPHA, 999))
                .add(new LllVar(111, "Reserved ISO 11", ALPHA, 999))
                .add(new LllVar(112, "Reserved National 4", ALPHA, 999))
                .add(new LllVar(113, "Reserved National 5", ALPHA, 999))
                .add(new LllVar(114, "Reserved National 6", ALPHA, 999))
                .add(new LllVar(115, "Reserved National 7", ALPHA, 999))
                .add(new LllVar(116, "Reserved National 8", ALPHA, 999))
                .add(new LllVar(117, "Reserved National 9", ALPHA, 999))
                .add(new LllVar(118, "Reserved National 10", ALPHA, 999))
                .add(new LllVar(119, "Reserved National 11", ALPHA, 999))
                .add(new LllVar(120, "Private Use 5", ALPHA, 999))
                .add(new LllVar(121, "Private Use 6", ALPHA, 999))
                .add(new LllVar(122, "Private Use 7", ALPHA, 999))
                .add(new LllVar(123, "POS Data Code", ALPHA, 999))
                .add(new LllVar(124, "Private Use 8", ALPHA, 999))
                .add(new LllVar(125, "Private Use 9", ALPHA, 999))
                .add(new LllVar(126, "Private Use 10", ALPHA, 999))
                .add(new LllVar(127, "Private Use 11", ALPHA, 999))
                .add(new Fixed(128, "MAC 2", BINARY, 8))
                .build();
    }
}
